# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor the master branch
  - package-ecosystem: "gradle" # or "docker", "pip", etc.
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
    # 👇 Add this section to group updates
    groups:
      all-dependencies:
        patterns:
          - "*" # Groups ALL dependencies in this ecosystem into one PR
      production-dependencies:
        patterns:
          - "*"
        dependency-type: "production" # Groups only production deps
        
  # Monitor the staging branch
  - package-ecosystem: "gradle" # or "docker", "pip", etc.
    directory: "/"
    target-branch: "staging"
    schedule:
      interval: "weekly"
    # 👇 Add this section to group updates
    groups:
      all-dependencies:
        patterns:
          - "*" # Groups ALL dependencies in this ecosystem into one PR
      production-dependencies:
        patterns:
          - "*"
        dependency-type: "production" # Groups only production deps
        
